/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { LessonData } from './types';

export const ALPHABET_DATA: LessonData[] = [
  {
    letter: 'A',
    word: 'Apple',
    imageKeyword: 'apple',
    questions: [
      { type: 'identity', question: 'What is it?', answer: "It's an apple." },
      { type: 'color', question: 'What color is it?', answer: 'It is Red.' },
      { type: 'like', question: 'Do you like it?', answer: 'Yes, I do.' },
      { type: 'location', question: 'Where do you see it?', answer: 'I see it on the tree.' },
      { type: 'count', question: 'How many apples are there?', answer: 'There is one apple.' },
    ],
  },
  {
    letter: 'B',
    word: 'Ball',
    imageKeyword: 'football',
    questions: [
      { type: 'identity', question: 'What is it?', answer: "It's a ball." },
      { type: 'color', question: 'What color is it?', answer: "It's Blue, Yellow and Red." },
      { type: 'like', question: 'Do you like it?', answer: 'Yes, I do.' },
      { type: 'location', question: 'Where do you see it?', answer: 'I see it on the floor.' },
      { type: 'count', question: 'How many balls are there?', answer: 'There are three ball.' },
    ],
  },
  {
    letter: 'C',
    word: 'Cat',
    imageKeyword: 'kitten',
    questions: [
      { type: 'identity', question: 'What is it?', answer: "It's a cat." },
      { type: 'color', question: 'What color is it?', answer: "It's brown and orange." },
      { type: 'like', question: 'Do you like it?', answer: 'Yes, I do.' },
      { type: 'location', question: 'Where do you see it?', answer: 'I see it in the house' },
      { type: 'count', question: 'How many cats are there?', answer: 'There are two cats.' },
    ],
  },
  {
    letter: 'D',
    word: 'Dog',
    imageKeyword: 'puppy',
    questions: [
      { type: 'identity', question: 'What is it?', answer: "It's a dog." },
      { type: 'color', question: 'What color is it?', answer: "It's white." },
      { type: 'like', question: 'Do you like it?', answer: 'Yes, I do.' },
      { type: 'location', question: 'Where do you see it?', answer: 'I see it in my house.' },
      { type: 'count', question: 'How many dogs are there?', answer: 'There is one dog.' },
    ],
  },
  {
    letter: 'E',
    word: 'Elephant',
    imageKeyword: 'elephant',
    questions: [
      { type: 'identity', question: 'What is it?', answer: "It's an elephant." },
      { type: 'color', question: 'What color is it?', answer: "It's gray." },
      { type: 'like', question: 'Do you like it?', answer: 'Yes, I do.' },
      { type: 'location', question: 'Where do you see it?', answer: 'I see it In the zoo' },
      { type: 'count', question: 'How many elephants are there?', answer: 'There is one elephant.' },
    ],
  },
  {
    letter: 'F',
    word: 'Frog',
    imageKeyword: 'frog',
    questions: [
      { type: 'identity', question: 'What is it?', answer: "It's a frog." },
      { type: 'color', question: 'What color is it?', answer: "It's green." },
      { type: 'like', question: 'Do you like it?', answer: 'Yes, I do.' },
      { type: 'location', question: 'Where do you see it?', answer: 'I see it in the pond.' },
      { type: 'count', question: 'How many frogs are there?', answer: 'There is one frog.' },
    ],
  },
  {
    letter: 'G',
    word: 'Goat',
    imageKeyword: 'goat',
    questions: [
      { type: 'identity', question: 'What is it?', answer: "It's a goat." },
      { type: 'color', question: 'What color is it?', answer: "It's white." },
      { type: 'like', question: 'Do you like it?', answer: 'Yes, I do.' },
      { type: 'location', question: 'Where do you see it?', answer: 'I see it on the farm.' },
      { type: 'count', question: 'How many goats are there?', answer: 'There is one goat.' },
    ],
  },
  {
    letter: 'H',
    word: 'Horse',
    imageKeyword: 'horse',
    questions: [
      { type: 'identity', question: 'What is it?', answer: 'It is a horse.' },
      { type: 'color', question: 'What color is it?', answer: "It's brown." },
      { type: 'like', question: 'Do you like it?', answer: 'Yes, I do.' },
      { type: 'location', question: 'Where do you see it?', answer: 'I see it in the stable.' },
      { type: 'count', question: 'How many horses are there?', answer: 'There is one horse.' },
    ],
  },
  {
    letter: 'I',
    word: 'Igloo',
    imageKeyword: 'igloo',
    questions: [
      { type: 'identity', question: 'What is it?', answer: "It's an igloo." },
      { type: 'color', question: 'What color is it?', answer: "It's white." },
      { type: 'like', question: 'Do you like it?', answer: 'Yes, I do.' },
      { type: 'location', question: 'Where do you see it?', answer: 'I see it in the snow.' },
      { type: 'count', question: 'How many igloos are there?', answer: 'There is one igloo.' },
    ],
  },
  {
    letter: 'J',
    word: 'Juice',
    imageKeyword: 'orange-juice',
    questions: [
      { type: 'identity', question: 'What is it?', answer: "It's orange juice." },
      { type: 'color', question: 'What color is it?', answer: "It's orange." },
      { type: 'like', question: 'Do you like it?', answer: 'Yes, I do.' },
      { type: 'location', question: 'Where do you see it?', answer: "It's on the table." },
      { type: 'count', question: 'How many glasses are there?', answer: 'There is one glass of juice.' },
    ],
  },
  {
    letter: 'K',
    word: 'Kite',
    imageKeyword: 'kites',
    questions: [
      { type: 'identity', question: 'What is it?', answer: "It's a kite." },
      { type: 'color', question: 'What color is it?', answer: "It's yellow, blue and orange." },
      { type: 'like', question: 'Do you like it?', answer: 'Yes, I do.' },
      { type: 'location', question: 'Where do you see it?', answer: 'I see it in the sky.' },
      { type: 'count', question: 'How many kites are there?', answer: 'There are four kites.' },
    ],
  },
  {
    letter: 'L',
    word: 'Lion',
    imageKeyword: 'lion',
    questions: [
      { type: 'identity', question: 'What is it?', answer: "It's a lion." },
      { type: 'color', question: 'What color is it?', answer: "It's yellow." },
      { type: 'like', question: 'Do you like it?', answer: 'Yes, I do.' },
      { type: 'location', question: 'Where do you see it?', answer: 'I see it in the jungle.' },
      { type: 'count', question: 'How many lions are there?', answer: 'There is one lion.' },
    ],
  },
  {
    letter: 'M',
    word: 'Monkey',
    imageKeyword: 'monkey',
    questions: [
      { type: 'identity', question: 'What is it?', answer: "It's a monkey." },
      { type: 'color', question: 'What color is it?', answer: "It's brown." },
      { type: 'like', question: 'Do you like it?', answer: 'Yes, I do.' },
      { type: 'location', question: 'Where do you see it?', answer: 'I see it on the tree.' },
      { type: 'count', question: 'How many monkeys are there?', answer: 'There is one monkey.' },
    ],
  },
  {
    letter: 'N',
    word: 'Nose',
    imageKeyword: 'person-nose',
    questions: [
      { type: 'identity', question: 'What is it?', answer: "It's a nose." },
      { type: 'color', question: 'What color is it?', answer: "It's pink." },
      { type: 'like', question: 'Do you like it?', answer: 'Yes, I do.' },
      { type: 'location', question: 'Where do you see it?', answer: 'I see it on the face.' },
      { type: 'count', question: 'How many noses are there?', answer: 'There is one nose.' },
    ],
  },
  {
    letter: 'O',
    word: 'Octopus',
    imageKeyword: 'octopus',
    questions: [
      { type: 'identity', question: 'What is it?', answer: "It's an octopus." },
      { type: 'color', question: 'What color is it?', answer: "It's purple." },
      { type: 'like', question: 'Do you like it?', answer: 'Yes, I do.' },
      { type: 'location', question: 'Where do you see it?', answer: 'I see it in the sea.' },
      { type: 'count', question: 'How many octopuses are there?', answer: 'There is one octopus.' },
    ],
  },
  {
    letter: 'P',
    word: 'Penguin',
    imageKeyword: 'penguins',
    questions: [
      { type: 'identity', question: 'What is it?', answer: "It's a penguin." },
      { type: 'color', question: 'What color is it?', answer: "It's Black & White." },
      { type: 'like', question: 'Do you like it?', answer: 'Yes, I do.' },
      { type: 'location', question: 'Where do you see it?', answer: 'I see it in the ice.' },
      { type: 'count', question: 'How many penguins are there?', answer: 'There are 5 penguins.' },
    ],
  },
  {
    letter: 'Q',
    word: 'Queen',
    imageKeyword: 'queen-cartoon',
    questions: [
      { type: 'identity', question: 'What is it?', answer: "It's a queen." },
      { type: 'color', question: 'What color is it?', answer: "It's blue and white." },
      { type: 'like', question: 'Do you like it?', answer: 'Yes, I do.' },
      { type: 'location', question: 'Where do you see her?', answer: 'I see her in the castle.' },
      { type: 'count', question: 'How many queens are there?', answer: 'There is one queen.' },
    ],
  },
  {
    letter: 'R',
    word: 'Rabbit',
    imageKeyword: 'rabbit',
    questions: [
      { type: 'identity', question: 'What is it?', answer: "It's a rabbit." },
      { type: 'color', question: 'What color is it?', answer: "It's pink." },
      { type: 'like', question: 'Do you like it?', answer: 'Yes, I do.' },
      { type: 'location', question: 'Where do you see it?', answer: 'I see it in the garden.' },
      { type: 'count', question: 'How many rabbits are there?', answer: 'There is one rabbit.' },
    ],
  },
  {
    letter: 'S',
    word: 'Sun',
    imageKeyword: 'sun',
    questions: [
      { type: 'identity', question: 'What is it?', answer: "It's the sun." },
      { type: 'color', question: 'What color is it?', answer: "It's yellow." },
      { type: 'like', question: 'Do you like it?', answer: 'Yes, I do.' },
      { type: 'location', question: 'Where do you see it?', answer: 'I see it in the sky.' },
      { type: 'count', question: 'How many suns are there?', answer: 'There is one sun.' },
    ],
  },
  {
    letter: 'T',
    word: 'Tiger',
    imageKeyword: 'tiger',
    questions: [
      { type: 'identity', question: 'What is it?', answer: "It's a tiger." },
      { type: 'color', question: 'What color is it?', answer: "It's orange." },
      { type: 'like', question: 'Do you like it?', answer: 'Yes, I do.' },
      { type: 'location', question: 'Where do you see it?', answer: 'I see it in the forest.' },
      { type: 'count', question: 'How many tigers are there?', answer: 'There is one tiger.' },
    ],
  },
  {
    letter: 'U',
    word: 'Umbrella',
    imageKeyword: 'umbrella',
    questions: [
      { type: 'identity', question: 'What is it?', answer: "It's an umbrella." },
      { type: 'color', question: 'What color is it?', answer: "It's blue." },
      { type: 'like', question: 'Do you like it?', answer: 'Yes, I do.' },
      { type: 'location', question: 'Where do you see it?', answer: 'I see it in the rain.' },
      { type: 'count', question: 'How many umbrellas are there?', answer: 'There is one umbrella.' },
    ],
  },
  {
    letter: 'V',
    word: 'Violin',
    imageKeyword: 'violin',
    questions: [
      { type: 'identity', question: 'What is it?', answer: "It's a violin." },
      { type: 'color', question: 'What color is it?', answer: "It's brown." },
      { type: 'like', question: 'Do you like it?', answer: 'Yes, I do.' },
      { type: 'location', question: 'Where do you see it?', answer: 'I see it in the music room.' },
      { type: 'count', question: 'How many violins are there?', answer: 'There is one violin.' },
    ],
  },
  {
    letter: 'W',
    word: 'Whale',
    imageKeyword: 'whale',
    questions: [
      { type: 'identity', question: 'What is it?', answer: "It's a whale." },
      { type: 'color', question: 'What color is it?', answer: "It's blue." },
      { type: 'like', question: 'Do you like it?', answer: 'Yes, I do.' },
      { type: 'location', question: 'Where do you see it?', answer: 'I see it in the ocean.' },
      { type: 'count', question: 'How many whales are there?', answer: 'There is one whale.' },
    ],
  },
  {
    letter: 'X',
    word: 'Xylophone',
    imageKeyword: 'xylophone',
    questions: [
      { type: 'identity', question: 'What is it?', answer: "It's a xylophone." },
      { type: 'color', question: 'What color is it?', answer: "It's multicolor." },
      { type: 'like', question: 'Do you like it?', answer: 'Yes, I do.' },
      { type: 'location', question: 'Where do you see it?', answer: 'I see it at school.' },
      { type: 'count', question: 'How many xylophones are there?', answer: 'There is one xylophone.' },
    ],
  },
  {
    letter: 'Y',
    word: 'Yo-yo',
    imageKeyword: 'yoyo',
    questions: [
      { type: 'identity', question: 'What is it?', answer: "It's a yo-yo." },
      { type: 'color', question: 'What color is it?', answer: "It's red." },
      { type: 'like', question: 'Do you like it?', answer: 'Yes, I do.' },
      { type: 'location', question: 'Where do you see it?', answer: 'I see it at school.' },
      { type: 'count', question: 'How many yo-yos are there?', answer: 'There is one yo-yo.' },
    ],
  },
  {
    letter: 'Z',
    word: 'Zebra',
    imageKeyword: 'zebra',
    questions: [
      { type: 'identity', question: 'What is it?', answer: "It's a zebra." },
      { type: 'color', question: 'What color is it?', answer: "It's Black & White." },
      { type: 'like', question: 'Do you like it?', answer: 'Yes, I do.' },
      { type: 'location', question: 'Where do you see it?', answer: 'I see it in the zoo.' },
      { type: 'count', question: 'How many zebras are there?', answer: 'There are 6 zebras.' },
    ],
  },
];
